query project($id: String!) {
  project(id: $id) {
    services {
      edges {
        node {
          name
          serviceInstances {
            edges {
              node {
                healthcheckPath
                healthcheckTimeout
                latestDeployment {
                  id
                  staticUrl
                  status
                }
              }
            }
          }
        }
      }
    }
  }
}
